jobs: 
  build: 
    docker: 
      - 
        image: "python:3.7.3-stretch"
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"requirements.txt\" }}"
            - v1-dependencies-
      - 
        run: 
          command: |
              python3 -m venv ~/.devops
              . ~/.devops/bin/activate
              make install
              wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
          name: "Install Dependencies"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"requirements.txt\" }}"
          paths: 
            - ~/.devops
      - 
        run: 
          command: |-
              . ~/.devops/bin/activate
              make lint
          name: "Run Lint"
    working_directory: ~/repo
version: 2.1
